// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { APIResource } from '../core/resource';
import { APIPromise } from '../core/api-promise';
import { RequestOptions } from '../internal/request-options';

export class Content extends APIResource {
  submit(body: ContentSubmitParams, options?: RequestOptions): APIPromise<ContentSubmitResponse> {
    return this._client.post('/moderate', { body, ...options });
  }
}

export interface ContentSubmitResponse {
  /**
   * The author of the content if your account has authors enabled. Requires you to
   * send authorId when submitting content.
   */
  author: ContentSubmitResponse.Author | null;

  /**
   * Potentially modified content.
   */
  content: ContentSubmitResponse.Content;

  /**
   * The evaluation of the content after running the channel policies.
   */
  evaluation: ContentSubmitResponse.Evaluation;

  /**
   * Results of all insights enabled in the channel.
   */
  insights: Array<ContentSubmitResponse.SentimentInsight | ContentSubmitResponse.LanguageInsight>;

  /**
   * Metadata about the moderation request
   */
  meta: ContentSubmitResponse.Meta;

  /**
   * Results of all policies in the channel. Sorted by highest probability.
   */
  policies: Array<ContentSubmitResponse.ClassifierOutput | ContentSubmitResponse.EntityMatcherOutput>;

  /**
   * The recommendation for the content based on the evaluation.
   */
  recommendation: ContentSubmitResponse.Recommendation;

  /**
   * Policies that had errors
   */
  errors?: Array<ContentSubmitResponse.Error>;
}

export namespace ContentSubmitResponse {
  /**
   * The author of the content if your account has authors enabled. Requires you to
   * send authorId when submitting content.
   */
  export interface Author {
    /**
     * Author ID in Moderation API
     */
    id: string;

    /**
     * Block or suspension details, if applicable. Null if the author is enabled.
     */
    block: Author.Block | null;

    /**
     * Current author status
     */
    status: 'enabled' | 'suspended' | 'blocked';

    trust_level: Author.TrustLevel;

    /**
     * The author's ID from your system
     */
    external_id?: string | null;
  }

  export namespace Author {
    /**
     * Block or suspension details, if applicable. Null if the author is enabled.
     */
    export interface Block {
      /**
       * The moderators reason why the author was blocked or suspended.
       */
      reason?: string | null;

      /**
       * The timestamp until which they are blocked if the author is suspended.
       */
      until?: number | null;
    }

    export interface TrustLevel {
      /**
       * Author trust level (-1, 0, 1, 2, 3, or 4)
       */
      level: number;

      /**
       * True if the trust level was set manually by a moderator
       */
      manual: boolean;
    }
  }

  /**
   * Potentially modified content.
   */
  export interface Content {
    /**
     * The unique identifier for the content. Either the contentId provided by you or
     * an autogenerated ID.
     */
    id: string;

    /**
     * Whether any values have been masked.
     */
    masked: boolean;

    /**
     * The modified content, if any.
     */
    modified:
      | string
      | { [key: string]: unknown }
      | { [key: string]: Content.Text | Content.Image | Content.Video | Content.Audio }
      | null;
  }

  export namespace Content {
    /**
     * Text
     */
    export interface Text {
      /**
       * The content text
       */
      text: string;

      type: 'text';
    }

    /**
     * Image
     */
    export interface Image {
      type: 'image';

      /**
       * A public URL of the image content
       */
      url: string;
    }

    /**
     * Video
     */
    export interface Video {
      type: 'video';

      /**
       * A public URL of the video content
       */
      url: string;
    }

    /**
     * Audio
     */
    export interface Audio {
      type: 'audio';

      /**
       * The URL of the audio content
       */
      url: string;
    }
  }

  /**
   * The evaluation of the content after running the channel policies.
   */
  export interface Evaluation {
    /**
     * The probability that the content should be flagged.
     */
    flag_probability: number;

    /**
     * Whether the content was flagged by any policy.
     */
    flagged: boolean;

    /**
     * The severity score of the content. A higher score indicates more severe content.
     */
    severity_score: number;

    /**
     * Whether the content was flagged for Unicode spoofing.
     */
    unicode_spoofed?: boolean;
  }

  /**
   * Sentiment insight
   */
  export interface SentimentInsight {
    id: 'sentiment';

    probability: number;

    type: 'insight';

    value: 'positive' | 'neutral' | 'negative' | null;
  }

  /**
   * Language insight
   */
  export interface LanguageInsight {
    id: 'language';

    probability: number;

    type: 'insight';

    value: string | null;
  }

  /**
   * Metadata about the moderation request
   */
  export interface Meta {
    /**
     * The unique key of the channel where the content was handled. Either the channel
     * provided by you or automatically routed.
     */
    channel_key: string;

    status: 'success' | 'partial_success';

    timestamp: number;

    usage: number;

    processing_time?: string;
  }

  /**
   * Classifier policy.
   */
  export interface ClassifierOutput {
    /**
     * The unique identifier for the classifier output.
     */
    id: string;

    flagged: boolean;

    probability: number;

    type: 'classifier';

    /**
     * The keys of the flagged fields if submitting an object.
     */
    flagged_fields?: Array<string>;

    labels?: Array<ClassifierOutput.Label>;
  }

  export namespace ClassifierOutput {
    export interface Label {
      id: string;

      flagged: boolean;

      probability: number;
    }
  }

  /**
   * Entity matcher policy.
   */
  export interface EntityMatcherOutput {
    id: string;

    flagged: boolean;

    matches: Array<EntityMatcherOutput.Match>;

    probability: number;

    type: 'entity_matcher';

    flagged_fields?: Array<string>;
  }

  export namespace EntityMatcherOutput {
    export interface Match {
      match: string;

      probability: number;

      span: Array<number>;
    }
  }

  /**
   * The recommendation for the content based on the evaluation.
   */
  export interface Recommendation {
    /**
     * The action to take based on the recommendation
     */
    action: 'review' | 'allow' | 'reject';

    /**
     * The reason code for the recommendation. Can be used to display a reason to the
     * user.
     */
    reason_codes: Array<
      | 'severity_reject'
      | 'severity_review'
      | 'author_block'
      | 'dry_run'
      | 'trusted_allow'
      | 'untrusted_severity'
    >;
  }

  export interface Error {
    id: string;

    message: string;
  }
}

export interface ContentSubmitParams {
  /**
   * The content sent for moderation
   */
  content:
    | ContentSubmitParams.Text
    | ContentSubmitParams.Image
    | ContentSubmitParams.Video
    | ContentSubmitParams.Audio
    | ContentSubmitParams.Object;

  /**
   * The author of the content.
   */
  authorId?: string;

  /**
   * Provide a channel ID or key. Will use the project's default channel if not
   * provided.
   */
  channel?: string;

  /**
   * The unique ID of the content in your database.
   */
  contentId?: string;

  /**
   * For example the ID of a chat room or a post
   */
  conversationId?: string;

  /**
   * Do not store the content. The content won't enter the review queue
   */
  doNotStore?: boolean;

  /**
   * Any metadata you want to store with the content
   */
  metadata?: { [key: string]: unknown };

  /**
   * The meta type of content being moderated
   */
  metaType?: 'profile' | 'message' | 'post' | 'comment' | 'event' | 'product' | 'review' | 'other';

  /**
   * (Enterprise) override the channel policies for this moderation request only.
   */
  policies?: Array<
    | ContentSubmitParams.Toxicity
    | ContentSubmitParams.PersonalInformation
    | ContentSubmitParams.ToxicitySevere
    | ContentSubmitParams.Hate
    | ContentSubmitParams.Illicit
    | ContentSubmitParams.IllicitDrugs
    | ContentSubmitParams.IllicitAlcohol
    | ContentSubmitParams.IllicitFirearms
    | ContentSubmitParams.IllicitTobacco
    | ContentSubmitParams.IllicitGambling
    | ContentSubmitParams.Cannabis
    | ContentSubmitParams.Adult
    | ContentSubmitParams.Crypto
    | ContentSubmitParams.Sexual
    | ContentSubmitParams.Flirtation
    | ContentSubmitParams.Profanity
    | ContentSubmitParams.Violence
    | ContentSubmitParams.SelfHarm
    | ContentSubmitParams.Spam
    | ContentSubmitParams.SelfPromotion
    | ContentSubmitParams.Political
    | ContentSubmitParams.Religion
    | ContentSubmitParams.CodeAbuse
    | ContentSubmitParams.PiiMasking
    | ContentSubmitParams.URLMasking
    | ContentSubmitParams.Guideline
  >;

  /**
   * Unix timestamp (in milliseconds) of when the content was created. Use if content
   * is not submitted in real-time.
   */
  timestamp?: number;
}

export namespace ContentSubmitParams {
  /**
   * Text
   */
  export interface Text {
    /**
     * The content text
     */
    text: string;

    type: 'text';
  }

  /**
   * Image
   */
  export interface Image {
    type: 'image';

    /**
     * A public URL of the image content
     */
    url: string;
  }

  /**
   * Video
   */
  export interface Video {
    type: 'video';

    /**
     * A public URL of the video content
     */
    url: string;
  }

  /**
   * Audio
   */
  export interface Audio {
    type: 'audio';

    /**
     * The URL of the audio content
     */
    url: string;
  }

  /**
   * Object
   */
  export interface Object {
    /**
     * Values in the object. Can be mixed content types.
     */
    data: { [key: string]: Object.Text | Object.Image | Object.Video | Object.Audio };

    type: 'object';
  }

  export namespace Object {
    /**
     * Text
     */
    export interface Text {
      /**
       * The content text
       */
      text: string;

      type: 'text';
    }

    /**
     * Image
     */
    export interface Image {
      type: 'image';

      /**
       * A public URL of the image content
       */
      url: string;
    }

    /**
     * Video
     */
    export interface Video {
      type: 'video';

      /**
       * A public URL of the video content
       */
      url: string;
    }

    /**
     * Audio
     */
    export interface Audio {
      type: 'audio';

      /**
       * The URL of the audio content
       */
      url: string;
    }
  }

  export interface Toxicity {
    id: 'toxicity';

    flag: boolean;

    threshold?: number;
  }

  export interface PersonalInformation {
    id: 'personal_information';

    flag: boolean;

    threshold?: number;
  }

  export interface ToxicitySevere {
    id: 'toxicity_severe';

    flag: boolean;

    threshold?: number;
  }

  export interface Hate {
    id: 'hate';

    flag: boolean;

    threshold?: number;
  }

  export interface Illicit {
    id: 'illicit';

    flag: boolean;

    threshold?: number;
  }

  export interface IllicitDrugs {
    id: 'illicit_drugs';

    flag: boolean;

    threshold?: number;
  }

  export interface IllicitAlcohol {
    id: 'illicit_alcohol';

    flag: boolean;

    threshold?: number;
  }

  export interface IllicitFirearms {
    id: 'illicit_firearms';

    flag: boolean;

    threshold?: number;
  }

  export interface IllicitTobacco {
    id: 'illicit_tobacco';

    flag: boolean;

    threshold?: number;
  }

  export interface IllicitGambling {
    id: 'illicit_gambling';

    flag: boolean;

    threshold?: number;
  }

  export interface Cannabis {
    id: 'cannabis';

    flag: boolean;

    threshold?: number;
  }

  export interface Adult {
    id: 'adult';

    flag: boolean;

    threshold?: number;
  }

  export interface Crypto {
    id: 'crypto';

    flag: boolean;

    threshold?: number;
  }

  export interface Sexual {
    id: 'sexual';

    flag: boolean;

    threshold?: number;
  }

  export interface Flirtation {
    id: 'flirtation';

    flag: boolean;

    threshold?: number;
  }

  export interface Profanity {
    id: 'profanity';

    flag: boolean;

    threshold?: number;
  }

  export interface Violence {
    id: 'violence';

    flag: boolean;

    threshold?: number;
  }

  export interface SelfHarm {
    id: 'self_harm';

    flag: boolean;

    threshold?: number;
  }

  export interface Spam {
    id: 'spam';

    flag: boolean;

    threshold?: number;
  }

  export interface SelfPromotion {
    id: 'self_promotion';

    flag: boolean;

    threshold?: number;
  }

  export interface Political {
    id: 'political';

    flag: boolean;

    threshold?: number;
  }

  export interface Religion {
    id: 'religion';

    flag: boolean;

    threshold?: number;
  }

  export interface CodeAbuse {
    id: 'code_abuse';

    flag: boolean;

    threshold?: number;
  }

  export interface PiiMasking {
    id: 'pii';

    entities: { [key: string]: PiiMasking.Entities };
  }

  export namespace PiiMasking {
    export interface Entities {
      enable?: boolean;

      flag?: boolean;

      mask?: string;

      shouldMask?: boolean;

      [k: string]: unknown;
    }
  }

  export interface URLMasking {
    id: 'url';

    entities: { [key: string]: URLMasking.Entities };
  }

  export namespace URLMasking {
    export interface Entities {
      enable?: boolean;

      flag?: boolean;

      mask?: string;

      shouldMask?: boolean;

      [k: string]: unknown;
    }
  }

  export interface Guideline {
    id: 'guideline';

    flag: boolean;

    guidelineKey: string;

    instructions: string;

    threshold?: number;
  }
}

export declare namespace Content {
  export {
    type ContentSubmitResponse as ContentSubmitResponse,
    type ContentSubmitParams as ContentSubmitParams,
  };
}
